### ISSUE TITLE
Create a repository for Adaptive App Generator

### ISSUE THREAD

**Issue by ferranvila** [AdaptiveMe/adaptive-arp-javascript#1]
This repository allocates the files of Adaptive Generator for Yeoman (http://yeoman.io/generators/)

ex: https://github.com/yeoman/generator-angular

**Comment by ferranvila** [comment]
IMPORTANT: The name of the repo should be: generator-name (where name is the name of your generator)
http://yeoman.io/authoring/

**Comment by ferranvila** [comment]
repo's name: **generator-adaptive**

**Comment by carloslozano** [comment]
Created -> https://github.com/AdaptiveMe/generator-adaptive
