### ISSUE TITLE
Create a repository for Adaptive Javascript Dependency

### ISSUE THREAD

**Issue by ferranvila** [AdaptiveMe/adaptive-arp-javascript#2]
Create a repository to allocate the distribution files of the Adaptive Javascript/Typescript library for Bower (http://bower.io/search/)

ex: https://github.com/angular/bower-angular

**Comment by ferranvila** [comment]
repo's name: **bower-adaptive**

**Comment by carloslozano** [comment]
Created -> https://github.com/AdaptiveMe/bower-adaptive
